import { Anek_Devanagari, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import { StoreProvider } from "@/redux/StoreProvider";
import BreakingNews from "@/components/breaking-news/BreakingNews";
import SliderAds from "@/components/ads/SliderAds";

const inter = Inter({ subsets: ["latin"] });
const aneka = Anek_Devanagari({ subsets: ["devanagari"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={aneka.className}>
          <Navbar />
          <SliderAds />
          <BreakingNews />
          {children}</body>
      </html>
    </StoreProvider>
  );
}
