
// const data = [
//     "Big News",
//     "state",
//     "apna jila",
//     "Technology",
//     "Crime",
//     "Country",
//     "Sports",
//     "Entertainment",
//     "Astrology",
//     "Carrier",
//     "Religion",
//     // "Politics",
//     "World",
//     "Cricket",
//     "Bollywood",
//     "Health",
// ]
export const categoryData = [
    {english: 'big news', hindi: 'बड़ी खबर'},
    {english: 'technology', hindi: 'टैकनोलजी'},
    {english: 'crime', hindi: 'क्राइम'},
    {english: 'country', hindi: 'देश'},
    {english: 'sports', hindi: 'खेल कूद'},
    {english: 'entertainment', hindi: 'मनोरंजन'},
    {english: 'astrology', hindi: 'राशिफल'},
    {english: 'carrier', hindi: 'करियर'},
    {english: 'religion', hindi: 'धर्म'},
    {english: 'world', hindi: 'विदेश'},
    {english: 'cricket', hindi: 'क्रिकेट'},
    {english: 'bollywood', hindi: 'बॉलीवुड'},
    {english: 'health', hindi: 'स्वास्थ्य'},
]